# Generated by Django 3.0.7 on 2020-06-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200624_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 22, 11, 24, 375911)),
        ),
    ]
