# Generated by Django 3.0.7 on 2020-06-24 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200624_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 22, 19, 28, 615588)),
        ),
    ]
